from ubuntu:noble-20240801 as eccodes-build
# TODO remove after eccodes in wheel
workdir /eccodes
run apt update && apt install -y cmake clang libaec0 libaec-dev fcc curl
run curl https://confluence.ecmwf.int/download/attachments/45757960/eccodes-2.35.1-Source.tar.gz?api=v2 --output eccodes.tar.gz && tar xzf eccodes.tar.gz && mkdir -p build /fiab/eccodes && cd build && cmake -DCMAKE_INSTALL_PREFIX=/fiab/eccodes ../eccodes-2.35.1-Source && make && make install

from ubuntu:noble-20240801
# TODO remove after eccodes in wheel
env ECCODES_DIR=/fiab/eccodes
copy --from=eccodes-build /fiab/eccodes /fiab/eccodes/

# system prep
run apt update && apt install -y curl libaec0 vim # NOTE libaec is for eccodes, vim for me

# runtime dependency: assumes to be mounted, as is .ecmwfapirc
env FIAB_MODEL_REPO=/fiab/models

# TODO eventually remove: wheel should be pip installed, fiab.sh curl-downloaded
copy dist/forecast_in_a_box-0.0.1-py3-none-any.whl forecast_in_a_box-0.0.1-py3-none-any.whl
copy fiab.sh fiab.sh

# entrypoint
entrypoint ["/fiab.sh"]
